# -*- coding: utf-8 -*-
"""code_02_equivalence_rb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kHFGSuXnCpFLJ5h8VHfDpDsVr662YTs
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# Date: April 4, 2026

import numpy as np
import matplotlib.pyplot as plt
import csv

# ---------------------------------------------------------
# Model A: Shiftless Collatz (Integer Arithmetic)
# ---------------------------------------------------------
def generate_shiftless_history(seed, steps):
    """ Generates Shiftless trajectory using standard integer arithmetic. """
    n = seed
    history = []
    for _ in range(steps + 1):
        history.append(n)
        lsb = n & -n
        n = 3 * n + lsb
    return history

# ---------------------------------------------------------
# Model B: True RB Polynomial in Z[x] (Delayed Carry)
# ---------------------------------------------------------
def generate_rb_polynomial_history(seed, steps):
    """
    Generates trajectory using polynomial arithmetic in Z[x].
    Carries are NOT resolved immediately; they accumulate as coefficients > 1.
    P_{k+1}(x) = (x+1)P_k(x) + x^{LSB_pos}
    """
    bits = [int(b) for b in bin(seed)[2:][::-1]] # LSB at index 0
    p = np.array(bits, dtype=np.int64)

    history_vals = []
    history_max_coeffs = []

    for _ in range(steps + 1):
        # Evaluate P(x) at x=2 to get the integer value (Carry Release)
        val = sum(int(c) * (2**i) for i, c in enumerate(p))
        history_vals.append(val)
        history_max_coeffs.append(int(np.max(p)) if len(p) > 0 else 0)

        # Find LSB from the evaluated integer value
        lsb = val & -val
        lsb_pos = lsb.bit_length() - 1 if val > 0 else 0

        # Polynomial multiplication: P(x) * (x+1)
        shifted = np.zeros(len(p) + 1, dtype=np.int64)
        shifted[1:] = p
        original = np.zeros(len(p) + 1, dtype=np.int64)
        original[:-1] = p

        # Z[x] addition: Carries accumulate here instead of shifting
        p_next = shifted + original

        # Inject noise x^{LSB_pos}
        if lsb_pos >= len(p_next):
            ext = np.zeros(lsb_pos + 1, dtype=np.int64)
            ext[:len(p_next)] = p_next
            p_next = ext
        p_next[lsb_pos] += 1

        p = p_next

    return history_vals, history_max_coeffs

# ---------------------------------------------------------
# Utility: Export Verification Results (CSV & High-Res PNG)
# ---------------------------------------------------------
def export_rb_verification_results(seed, steps):
    """ Computes the equivalence and exports the results to CSV and PNG. """
    # 1. Generate histories
    hist_sft = generate_shiftless_history(seed, steps)
    hist_rb_vals, hist_rb_coeffs = generate_rb_polynomial_history(seed, steps)

    # 2. Prepare data for export
    cell_text = []
    for k in range(steps + 1):
        sft_n = hist_sft[k]
        rb_val = hist_rb_vals[k]
        max_coeff = hist_rb_coeffs[k]

        # Verify strict mathematical equivalence (A = B)
        status = "MATCH" if sft_n == rb_val else "FAIL"

        cell_text.append([str(k), str(sft_n), str(rb_val), str(max_coeff), status])

    col_labels = ["Step k", "Shiftless N (Integer)", "True RB P(2)", "Max Coeff in P(x)", "Status"]

    # --- 3. Export to CSV ---
    csv_filename = f"equivalence_rb_seed_{seed}.csv"
    with open(csv_filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(col_labels)
        writer.writerows(cell_text)
    print(f"Success! Exported numerical data to: {csv_filename}")

    # --- 4. Export to High-Res PNG (Table Visualization) ---
    fig_height = max(6, (steps + 1) * 0.3)
    fig, ax = plt.subplots(figsize=(12, fig_height), dpi=300)
    ax.axis("tight")
    ax.axis("off")

    table = ax.table(cellText=cell_text, colLabels=col_labels, loc="center", cellLoc="center")
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1.2, 1.5)

    # Styling: Header
    for j in range(len(col_labels)):
        table[0, j].set_text_props(weight="bold", color="white")
        table[0, j].set_facecolor("#333333")

    # Styling: Data Rows
    for i in range(1, steps + 2):
        for j in range(len(col_labels)):
            if i % 2 == 0:
                table[i, j].set_facecolor("#f9f9f9")

            # Highlight coefficient accumulation (Delayed Carry > 1)
            coeff_val = int(cell_text[i-1][3])
            if j == 3 and coeff_val > 1:
                table[i, j].set_facecolor("#e3f2fd")
                table[i, j].set_text_props(weight="bold", color="#1565c0")

    # Ensure title does not overlap
    plt.suptitle(f"Z[x] Polynomial Equivalence Verification (Seed: {seed})", fontweight="bold", fontsize=16, y=0.98)
    plt.tight_layout(rect=[0, 0, 1, 0.96])

    png_filename = f"equivalence_rb_seed_{seed}.png"
    plt.savefig(png_filename, bbox_inches="tight", facecolor="white")
    print(f"Success! Exported rendered table to: {png_filename}")
    plt.close()

# ---------------------------------------------------------
# Main Execution
# ---------------------------------------------------------
def main(seed=27, steps=41):
    print("Initiating True RB equivalence verification...")
    export_rb_verification_results(seed, steps)

if __name__ == "__main__":
    main(seed=27, steps=41)

