# -*- coding: utf-8 -*-
"""code_03_3n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fN31JnK8xqNe0ve3U1uxxLpomH9wQCp
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# Date: April 4, 2026

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

# ---------------------------------------------------------
# Utility: Convert integer to fixed-length bit array
# ---------------------------------------------------------
def to_bit_array(n, length):
    """ Converts an integer to a right-aligned bit array. """
    bits = [int(b) for b in bin(n)[2:]]
    arr = np.zeros(length, dtype=np.int8)
    if len(bits) > 0:
        arr[-len(bits):] = bits
    return arr

# ---------------------------------------------------------
# Model A: Standard 3n (With Carries)
# ---------------------------------------------------------
def generate_standard_history(seed, steps):
    """ Generates evolution of standard 3^k multiplication. """
    history = []
    val = seed
    for _ in range(steps + 1):
        history.append(val)
        val *= 3
    return history

# ---------------------------------------------------------
# Model B: Carryless 3n in GF(2)
# ---------------------------------------------------------
def generate_carryless_history(seed, steps):
    """ Generates evolution of (x+1)^k in GF(2) (Rule 90). """
    p_bits = [int(b) for b in bin(seed)[2:][::-1]]
    p_k = np.array(p_bits, dtype=np.int8)
    history = []

    for _ in range(steps + 1):
        val = int("".join(map(str, p_k[::-1])), 2) if len(p_k) > 0 else 0
        history.append(val)
        shifted = np.zeros(len(p_k) + 1, dtype=np.int8)
        shifted[1:] = p_k
        original = np.zeros(len(p_k) + 1, dtype=np.int8)
        original[:-1] = p_k
        p_next = np.bitwise_xor(shifted, original)
        p_k = p_next

    return history

# ---------------------------------------------------------
# Main Visualization and Export
# ---------------------------------------------------------
def export_3n_comparison(seed=1, steps=64):
    """ Computes the evolution and exports the visual comparison to PNG. """
    hist_std = generate_standard_history(seed, steps)
    hist_cl = generate_carryless_history(seed, steps)

    max_val = max(max(hist_std), max(hist_cl))
    max_len = max(1, max_val.bit_length()) + 2

    def build_mat(hist):
        mat = np.zeros((len(hist), max_len), dtype=np.int8)
        for i, val in enumerate(hist):
            mat[i, :] = to_bit_array(val, max_len)
        return mat

    mat_std = build_mat(hist_std)
    mat_cl = build_mat(hist_cl)

    fig, axes = plt.subplots(1, 2, figsize=(16, 10), facecolor="#0a0a0a")
    cmap = ListedColormap(["#0a0a0a", "#00FFCC"])

    axes[0].imshow(mat_std, cmap=cmap, aspect="auto", interpolation="nearest")
    axes[0].set_title(f"Standard 3n (With Carries)\nSeed = {seed}  →  3^k", color="white", fontsize=14, pad=15)

    axes[1].imshow(mat_cl, cmap=cmap, aspect="auto", interpolation="nearest")
    axes[1].set_title(f"Carryless 3n in GF(2)\nSeed = {seed}  →  (x+1)^k  (Rule 90)", color="white", fontsize=14, pad=15)

    # X-axis tick settings (Right-aligned, LSB=0)
    tick_step = 50 if max_len > 100 else 10
    bit_labels = list(range(0, max_len, tick_step))
    x_positions = [max_len - 1 - b for b in bit_labels]

    for ax in axes:
        ax.set_xticks(x_positions)
        ax.set_xticklabels(bit_labels)
        ax.set_xlabel("Bit Position (MSB ←  → LSB=0)", color="gray")
        ax.tick_params(colors="gray", labelsize=8)
        for spine in ax.spines.values():
            spine.set_color("#333333")

    axes[0].set_ylabel("Step k", color="gray")

    # Use suptitle and adjust layout to prevent overlap
    plt.suptitle("The Origin of Chaos: Carry Avalanche vs Pure Order", color="white", fontsize=20, fontweight="bold", y=0.98)
    plt.tight_layout(rect=[0, 0, 1, 0.96])

    # Export to High-Res PNG
    png_filename = f"3n_seed_{seed}.png"
    plt.savefig(png_filename, dpi=300, facecolor="#0a0a0a", bbox_inches="tight")
    print(f"Success! Exported rendered plot to: {png_filename}")

    plt.show()

if __name__ == "__main__":
    export_3n_comparison(seed=1, steps=64)

