# -*- coding: utf-8 -*-
"""code_01_equivalence_shiftless.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zM9ySLDOQYM3qg6DmvAxx3vujIStk2nl
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# Date: April 4, 2026

import numpy as np
import matplotlib.pyplot as plt
import csv

# ---------------------------------------------------------
# Model A: Standard Collatz (Odd steps only)
# ---------------------------------------------------------
def generate_standard_odd_history(seed, steps):
    """ Generates the standard Collatz trajectory (odd numbers only). """
    n = seed if seed % 2 != 0 else seed + 1
    history = []
    for _ in range(steps + 1):
        history.append(n)
        n_next = 3 * n + 1
        # Right-shift until odd
        while n_next % 2 == 0 and n_next > 0:
            n_next //= 2
        n = n_next
    return history

# ---------------------------------------------------------
# Model B: Shiftless Collatz (3n + LSB)
# ---------------------------------------------------------
def generate_shiftless_history(seed, steps):
    """ Generates the Shiftless Collatz trajectory, retaining LSB weight. """
    n = seed
    history = []
    for _ in range(steps + 1):
        history.append(n)
        lsb = n & -n
        n = 3 * n + lsb
    return history

# ---------------------------------------------------------
# Utility: Export Verification Results (CSV & High-Res PNG)
# ---------------------------------------------------------
def export_verification_results(seed, steps):
    """ Computes the equivalence and exports the results to CSV and PNG. """
    # 1. Generate histories
    hist_std = generate_standard_odd_history(seed, steps)
    hist_sft = generate_shiftless_history(seed, steps)

    # 2. Prepare data for export
    cell_text = []
    for k in range(steps + 1):
        std_n = hist_std[k]
        sft_n = hist_sft[k]

       # Normalize Shiftless N by its LSB (equivalent to right-shifting)
        lsb = sft_n & -sft_n
        sft_odd = sft_n // lsb if lsb != 0 else sft_n

        # Verify strict mathematical equivalence
        status = "MATCH" if std_n == sft_odd else "FAIL"

        cell_text.append([str(k), str(std_n), str(sft_n), str(sft_odd), status])

    col_labels = ["Step k", "Standard Collatz", "Shiftless (N)", "N // LSB(N)", "Status"]

    # --- 3. Export to CSV ---
    csv_filename = f"equivalence_shiftless_seed_{seed}.csv"
    with open(csv_filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(col_labels)
        writer.writerows(cell_text)
    print(f"Success! Exported numerical data to: {csv_filename}")

    # --- 4. Export to High-Res PNG (Table Visualization) ---
    # Dynamically adjust figure height based on the number of steps
    fig_height = max(6, (steps + 1) * 0.3)
    fig, ax = plt.subplots(figsize=(12, fig_height), dpi=300)
    ax.axis("tight")
    ax.axis("off")

    # Draw the table
    table = ax.table(cellText=cell_text, colLabels=col_labels, loc="center", cellLoc="center")
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1.2, 1.5)

    # Styling: Header (dark grey)
    for j in range(len(col_labels)):
        table[0, j].set_text_props(weight="bold", color="white")
        table[0, j].set_facecolor("#333333")

    # Styling: Data Rows (zebra striping)
    for i in range(1, steps + 2):
        for j in range(len(col_labels)):
            if i % 2 == 0:
                table[i, j].set_facecolor("#f9f9f9")

            # Highlight Jackpot state (Power of 2) in the Shiftless model
            sft_val = hist_sft[i-1]
            if j == 2 and (sft_val & (sft_val - 1) == 0) and sft_val > 0 and i-1 > 0:
                table[i, j].set_facecolor("#ffffcc")
                table[i, j].set_text_props(weight="bold", color="#d32f2f")

    # suptitle places the title at the top of the entire figure, preventing overlap with the axis
    plt.suptitle(f"Numerical Equivalence Verification (Seed: {seed})", fontweight="bold", fontsize=16, y=0.98)

    # Use tight_layout to make sure everything fits well (adjust rect to make room for suptitle)
    plt.tight_layout(rect=[0, 0, 1, 0.96])

    png_filename = f"equivalence_shiftless_seed_{seed}.png"
    plt.savefig(png_filename, bbox_inches="tight", facecolor="white")
    print(f"Success! Exported rendered table to: {png_filename}")
    plt.close()

# ---------------------------------------------------------
# Main Execution
# ---------------------------------------------------------
def main(seed=27, steps=41):
    print("Initiating equivalence verification and exporting artifacts...")
    export_verification_results(seed, steps)

if __name__ == "__main__":
    main(seed=27, steps=41)

